/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucsd_cs_riffa_Fpga */

#ifndef _Included_edu_ucsd_cs_riffa_Fpga
#define _Included_edu_ucsd_cs_riffa_Fpga
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ucsd_cs_riffa_Fpga
 * Method:    jFpgaList
 * Signature: (Ledu/ucsd/cs/riffa/FpgaInfo;)I
 */
JNIEXPORT jint JNICALL Java_edu_ucsd_cs_riffa_Fpga_jFpgaList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_ucsd_cs_riffa_Fpga
 * Method:    jFpgaOpen
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_ucsd_cs_riffa_Fpga_jFpgaOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_ucsd_cs_riffa_Fpga
 * Method:    jFpgaClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_ucsd_cs_riffa_Fpga_jFpgaClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_ucsd_cs_riffa_Fpga
 * Method:    jFpgaSend
 * Signature: (JILjava/nio/ByteBuffer;IIIJ)I
 */
JNIEXPORT jint JNICALL Java_edu_ucsd_cs_riffa_Fpga_jFpgaSend
  (JNIEnv *, jobject, jlong, jint, jobject, jint, jint, jint, jlong);

/*
 * Class:     edu_ucsd_cs_riffa_Fpga
 * Method:    jFpgaRecv
 * Signature: (JILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_edu_ucsd_cs_riffa_Fpga_jFpgaRecv
  (JNIEnv *, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     edu_ucsd_cs_riffa_Fpga
 * Method:    jFpgaReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_ucsd_cs_riffa_Fpga_jFpgaReset
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
